### ISSUE TITLE
issue about build ROM

### ISSUE THREAD

**Issue by devhg** [fulgerul46/android_device_xiaomi_hennessy#1]
I  used your device tree to build Mokee ROM.  But ROM get stuck in the boot animation. What's the problem? Did you try to build other ROM in the past? Like Mokee, Sudamod, ResurrectionRemix and so on.

If you know what the problem is, you can contact me. My email address is zhangguohui6@gmail.com.

Looking forward to hearing from you soon.

**Comment by pgeorgef** [comment]
Just built ResurrectionRemix ,booted in the first try  ( https://drive.google.com/open?id=0B19jNsds8A2PVjktQTNOQjBDRlE ) ,have you applied the patches?

**Comment by devhg** [comment]
I have built RR,but the ril is boom,   
reboot will get struck in boot animation
you can look through  http://bbs.ydss.cn/thread-1015237-1-1.html   .  What bugs about your RR?

**Comment by pgeorgef** [comment]
Ril is working and it doesen't bootloop ,flash this gapps with it https://download.dirtyunicorns.com/gapps/Banks/ ,last version of magisk ,after that go in accesibility ,turn 60fps on ,and give the 60fps app root access

**Comment by devhg** [comment]
It may be my computer problem. I'll try again. You can try Mokee sudamod and so on. It may be better than lineageos.
You're great, expect you to fix your fingerprints, and expect you to build Android N, come on!
In China, very few developers touch MTK, because they are afraid of bugs, so we can only wait for the developers  of other countries.
After seeing the news of Hennessy marshmallow. I am very pleased. Come on!
About Android N ,we can refer to hermes,letv1s.
